/*
 Navicat Premium Data Transfer

 Source Server         : Seateller
 Source Server Type    : PostgreSQL
 Source Server Version : 120011
 Source Host           : 192.168.0.142:5432
 Source Catalog        : seateller
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 120011
 File Encoding         : 65001

 Date: 30/08/2022 18:07:00
*/


-- ----------------------------
-- Table structure for transfer_reverse
-- ----------------------------
DROP TABLE IF EXISTS "public"."transfer_reverse";
CREATE TABLE "public"."transfer_reverse" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "amount" varchar(255) COLLATE "pg_catalog"."default",
  "authoriser" varchar(255) COLLATE "pg_catalog"."default",
  "chg_id" varchar(255) COLLATE "pg_catalog"."default",
  "co_code" varchar(255) COLLATE "pg_catalog"."default",
  "create_date" timestamp(6),
  "credit_account" varchar(255) COLLATE "pg_catalog"."default",
  "currency" varchar(255) COLLATE "pg_catalog"."default",
  "customer_code" varchar(255) COLLATE "pg_catalog"."default",
  "de_code" varchar(255) COLLATE "pg_catalog"."default",
  "debit_account" varchar(255) COLLATE "pg_catalog"."default",
  "error_description" varchar(255) COLLATE "pg_catalog"."default",
  "fee_code" varchar(255) COLLATE "pg_catalog"."default",
  "inputter" varchar(255) COLLATE "pg_catalog"."default",
  "note" varchar(255) COLLATE "pg_catalog"."default",
  "reason" varchar(255) COLLATE "pg_catalog"."default",
  "reverse_code" varchar(255) COLLATE "pg_catalog"."default",
  "reverse_id" varchar(255) COLLATE "pg_catalog"."default",
  "status" varchar(255) COLLATE "pg_catalog"."default",
  "status_inau" varchar(255) COLLATE "pg_catalog"."default",
  "t24_id_response" varchar(255) COLLATE "pg_catalog"."default",
  "time_reject" timestamp(6),
  "time_sla_authorise" varchar(255) COLLATE "pg_catalog"."default",
  "update_date" timestamp(6),
  "chg_code" varchar(255) COLLATE "pg_catalog"."default",
  "type_search" varchar(255) COLLATE "pg_catalog"."default"
)

-- ----------------------------
-- Primary Key structure for table transfer_reverse
-- ----------------------------
ALTER TABLE "public"."transfer_reverse" ADD CONSTRAINT "transfer_reverse_pkey" PRIMARY KEY ("id");
;
